# Use a imagem base do Node.js
FROM node:latest

# Define o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copia o arquivo package.json e package-lock.json para o diretório de trabalho
COPY . /app

# Instala as dependências do projeto
RUN npm install --omit=dev

# Copia todos os arquivos do diretório atual (que contém o Dockerfile) para o diretório de trabalho do contêiner
COPY . .

# Define o comando a ser executado quando o contêiner for iniciado
CMD ["npm", "run", "start", " --omit=dev"]
# --max-old-space-size=300

EXPOSE 3000