version: '3'
services:
  apigateway:
    extends:
      file: docker/docker-compose.api.yml
      service: apigateway
  database:
    extends:
      file: docker/docker-compose.database.yml
      service: database

networks:
  main-network:  
   
