version: '3'
services:
  database:
    extends:
      file: docker/docker-compose.database.yml
      service: database
  apigateway:
    extends:
      file: docker/docker-compose.api.yml
      service: apigateway
networks:
  main-network: