version: '3'
services:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=e8xf1538fet
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

   
