version: '3'
services:
  apigateway:
    image: node:latest
    command: sh -c "npm install && npm run start"
    working_dir: /app
    volumes:
      - ../:/app
    ports:
      - 3000:3000
    networks:
      - main-network  
    depends_on:
      - database