version: '3'
services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: e8xf1538fet
      POSTGRES_DB: postgres
    volumes:
      - ../scripts:/docker-entrypoint-initdb.d  #create tables
    networks:
      - main-network  
    ports:
      - "5432:5432"
   
