version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    networks:
      - app-network
    depends_on:
      - api-gateway

  api-gateway:
    build: ./api-gateway
    ports:
      - 4000:4000
    networks:
      - app-network
    depends_on:
      - cadastro
      - doacoes

  cadastro:
    build: ./cadastro
    networks:
      - app-network
    depends_on:
      - db

  doacoes:
    build: ./doacoes
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres-data:
